import type { MenuOption } from "naive-ui";

export const menuOptions: MenuOption[] = [
  {
    label: "医德医风",
    key: "1",
    children: [
      {
        label: "组织体系",
        key: "11",
        iconClass: "icon-biaoqian1",
        href: "/corporateConduct/organizational",
        openMode: "FRAME_INNER",
      },
      {
        label: "规章制度",
        key: "12",
        iconClass: "icon-biaoqian1",
        href: "/corporateConduct/regulations",
        openMode: "FRAME_INNER",
      },
      {
        label: "开展活动",
        key: "15",
        iconClass: "icon-biaoqian1",
        href: "/conductActivity/activity",
        openMode: "FRAME_INNER",
      },
      {
        label: "自查自纠",
        key: "16",
        iconClass: "icon-biaoqian1",
        href: "/conductActivity/commitment",
        openMode: "FRAME_INNER",
      },
      {
        label: "自查自纠报告",
        key: "17",
        iconClass: "icon-biaoqian1",
        href: "/conductActivity/selfCheck",
        openMode: "FRAME_INNER",
      },
      {
        label: "个人承诺书",
        key: "18",
        iconClass: "icon-biaoqian1",
        href: "/conductActivity/personalCommitment",
        openMode: "FRAME_INNER",
      },
      {
        label: "行风工作会议",
        key: "20",
        iconClass: "icon-biaoqian1",
        href: "/workMeeting",
        openMode: "FRAME_INNER",
      },
      {
        label: "医德医风档案",
        key: "19",
        iconClass: "icon-biaoqian1",
        href: "/ethicsArchive",
        openMode: "FRAME_INNER",
        children: [
          {
            label: "我的医德档案",
            key: "191",
            iconClass: "icon-biaoqian1",
            href: "/ethicsArchive/my",
            openMode: "FRAME_INNER",
          },
          {
            label: "全员医德档案",
            key: "192",
            iconClass: "icon-biaoqian1",
            href: "/ethicsArchive/all",
            openMode: "FRAME_INNER",
          },
        ],
      },
      {
        label: "管理用户列表",
        key: "13",
        iconClass: "icon-biaoqian1",
        href: "/userRole/management",
        openMode: "FRAME_INNER",
      },
      {
        label: "审核用户列表",
        key: "14",
        iconClass: "icon-biaoqian1",
        href: "/userRole/audit",
        openMode: "FRAME_INNER",
      },
      {
        label: "行为监督",
        key: "21",
        iconClass: "icon-biaoqian1",
        href: "/behaviorSupervision",
        openMode: "FRAME_INNER",
        children: [
          {
            label: "监督规则",
            key: "211",
            iconClass: "icon-biaoqian1",
            href: "/behaviorSupervision/rules",
            openMode: "FRAME_INNER",
          },
          {
            label: "个人申报",
            key: "212",
            iconClass: "icon-biaoqian1",
            href: "/behaviorSupervision/personalApply",
            openMode: "FRAME_INNER",
          },
          {
            label: "分值审核",
            key: "213",
            iconClass: "icon-biaoqian1",
            href: "/behaviorSupervision/scoreAudit",
            openMode: "FRAME_INNER",
          },
          {
            label: "分值录入",
            key: "214",
            iconClass: "icon-biaoqian1",
            href: "/behaviorSupervision/scoreEntry",
            openMode: "FRAME_INNER",
          },
          {
            label: "分值查询",
            key: "215",
            iconClass: "icon-biaoqian1",
            href: "/behaviorSupervision/scoreQuery",
            openMode: "FRAME_INNER",
          },
        ],
      },
    ],
  },
];
